name: AWS S3 Static Site Deploy
on:
  pull_request:
    branches: [master]
jobs:
  build_and_aws_deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.x]
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PATHS: '/*'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Get branch name
        id: vars
        run: echo ::set-output name=branch::${{ github.event.pull_request.head.ref }}

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: export BRANCH_NAME=${{ steps.vars.outputs.branch }} && yarn build:uat

      - name: AWS S3 Deploy
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks
        # env:
        #   SOURCE_DIR: './build/'

      # - name: Clear Cloudfront Cache
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }} --paths "/*"
